baseURL = "https://fantomeszine.com"
languageCode = "en-ca"
theme = "fantomes"
title = "Fantômes"

[params]
      image = "/img/preview.png"
      author = "Lizbeth Poirier"
      desc = "Fantômes is a collaborative ghost story zine, bringing together story-telling, poetry, folklore, illustration and photography in small cobbled-together publication."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
