name = "Fantomes"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://fantomeszine.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Lizbeth Poirier-Morissette"
  homepage = "https://ritualdust.com"
